### ISSUE TITLE
Error: cannot create directory ‘/home/postgres’: Permission denied

### ISSUE THREAD

**Issue by michaelrommel** [timescale/timescaledb-docker-ha#266]
Hi,

I have a very simple setup, just using the normal docker-ce installation on debian bullseye running under root privileges. No special configurations. I created a postgres user with uid 1003 and a postgres group with gid 1004 and a directory for the data:

```
root@seagull:/var/lib# find postgres/ -ls
   131534      4 drwxr-xr-x   3 postgres postgres     4096 Jun 13 15:30 postgres/
   132125      4 drwxr-xr-x   2 postgres postgres     4096 Jun 13 15:30 postgres/data
```

My docker-compose file is similarly simple:
```
version: '3.0'

services:
  db:
    image: timescale/timescaledb-ha:pg14-latest
    user: "1003:1004"
    ports:
      - 5432:5432/tcp
    volumes:
      - /var/lib/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: somesecretstring
```

Now, when I do a docker compose up the container immediately fails with:

```
root@seagull:/srv/containers/monitoring# docker compose up
[+] Running 2/2
 ⠿ Network monitoring_default  Created                                                                              0.1s
 ⠿ Container monitoring-db-1   Created                                                                              0.1s
Attaching to monitoring-db-1
monitoring-db-1  | mkdir: cannot create directory ‘/home/postgres’: Permission denied
monitoring-db-1 exited with code 1
```

How is this container to be used? Is it only for Zalando or something?

I was just looking for an image with promscale and this does not seem to work.

Can you provide some documentation on how to use it or otherwise put a disclaimer somewhere that this is not for public use?

Thanks!

  Michael.
