### ISSUE TITLE
Databases are deleted after image update

### ISSUE THREAD

**Issue by CM000n** [timescale/timescaledb-docker-ha#290]
Hello all,
First of all, thank you very much for your work.
I switched from the official Timescale Docker image with Postgis to your HA Docker image some time ago.

My setup looks like this: I have pinned the timescale version to 14, and a Watchtower container ensures a regular update.
Here is an excerpt of my Docker compose.yaml

```yaml
  timescale:
    container_name: timescale
    restart: always
    image: timescale/timescaledb-ha:pg14-latest
    networks:
      - proxyv6
    volumes:
      - /srv/dev-disk-by-uuid-someuuid/data/docker_data/timescale_ha:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=MYUSER
      - POSTGRES_PASSWORD=MYPASSWORD
    ports:
      - "5442:5432"

  watchtower:
    container_name: watchtower
    restart: always
    image: v2tec/watchtower
    networks:
      - proxyv6
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 240
```

This setup has always worked wonderfully with the original Timescaledb image. The databases I created remained intact even after an image update. With timescaledb-docker-ha, however, the databases are now gone after every image update :-(
Am I missing something here? Do I have to make an additional setting for timescaledb-docker-ha?

Unfortunately, I can't get any meaningful logs at the moment because I usually notice the image update too late. But I'll see if I can reproduce it by switching off the watchtower container and performing a manual update.

In any case, thanks in advance for your help!
