### ISSUE TITLE
deployment as in docker stack has data volume permission problems

### ISSUE THREAD

**Issue by pezzacolori** [timescale/timescaledb-docker-ha#311]
I need Timescale together with postgis.

By deploying  timescale/timescaledb-ha:pg14-latest  
in a docker stack  

  postgres:
    ports:
      - 54xx:5432
    image: timescale/timescaledb-ha:pg14-latest
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=xxxx
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - box-net

it raises an error:

mkdir: cannot create directory ‘/var/lib/postgresql/data/pgdata’: Permission denied

On the contrary using the     timescale/timescaledb:latest-pg14  
image there are no problems and the database is created automatically.

Maybe it is a problem linked to the packaged linux version (apline in plain timescaledb, ubuntu in timescaledb-ha) ?
Do you know how to solve the issue?

Cheers,
Boris

**Comment by VMM-Mtech** [comment]
See #272 and #290. Is your case that you have created the volume with the standard image, and then mounting it to the ha container? Then the root cause seems to be the fact that standard image uses uid:gid 70:70, and the ha container uses 1000:1000.

**Comment by graveland** [comment]
Let me know if the latest image works for you now!

My testing with ```--user 1234:1111 -v `pwd`/db:/home/pgdata -ePGDATA=/home/pgdata <image>```, stopping, and restarting with different --user values created a database, and then successfully restarted. Hopefully this will help?

The postgresql user is still always `postgres`, but nss-wrapper tricks postgresql into thinking ownership is correct. You should have an easier time using this image and just modifying `PGDATA` and `--user`. Specifically try to avoid using locations in the default `postgres` user home directory `/home/postgres` when you're using either a different user, or a different `PGDATA` value.

**Comment by samul-1** [comment]
I'm running into the same issue. Here's how I've defined the service in my docker-compose:

```
  timescaledb:
    image: timescale/timescaledb-ha:pg16
    volumes:
      - ./timescaledb_data:/home/postgres/pgdata/data/
    environment:
      POSTGRES_USER: puser
      POSTGRES_PASSWORD: ppass
    expose:
      - "5432"
    ports:
      - "5433:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"
```

Here's what I get when running the container:

```
timescaledb-1  | using nss-wrapper
timescaledb-1  | The files belonging to this database system will be owned by user "postgres".
timescaledb-1  | This user must also own the server process.
timescaledb-1  | 
timescaledb-1  | The database cluster will be initialized with locale "C.UTF-8".
timescaledb-1  | The default database encoding has accordingly been set to "UTF8".
timescaledb-1  | The default text search configuration will be set to "english".
timescaledb-1  | 
timescaledb-1  | Data page checksums are disabled.
timescaledb-1  | 
timescaledb-1  | initdb: error: could not change permissions of directory "/home/postgres/pgdata/data": Operation not permitted
timescaledb-1  | fixing permissions on existing directory /home/postgres/pgdata/data ... 
timescaledb-1 exited with code 1
```

How do I make it work?

**Comment by graveland** [comment]
You should pick a path outside of `/home/postgres` for your data volume, then add PGDATA=<new-path> in the environment.

**Comment by samul-1** [comment]
> You should pick a path outside of `/home/postgres` for your data volume
but isn't it where the data is stored? Does adding a PGDATA env variable change where the data is stored?

**Comment by graveland** [comment]
Data can be stored basically anywhere, and setting PGDATA tells postgresql where it is. The contents of `/home/postgres` already exists, and that's what is causing problems changing permissions with the unprivileged container.

**Comment by samul-1** [comment]
> Data can be stored basically anywhere, and setting PGDATA tells postgresql where it is. The contents of `/home/postgres` already exists, and that's what is causing problems changing permissions with the unprivileged container.

I did this
```
  timescaledb:
    image: timescale/timescaledb-ha:pg16
    userns_mode: "host"
    volumes:
      - ./timescaledb_data:/pgdata/data/
    environment:
      POSTGRES_USER: puser
      POSTGRES_PASSWORD: ppass
      PGDATA: /pgdata/data/
```

and now the output is:

```
timescaledb-1  | using nss-wrapper
timescaledb-1  | The files belonging to this database system will be owned by user "postgres".
timescaledb-1  | This user must also own the server process.
timescaledb-1  | 
timescaledb-1  | The database cluster will be initialized with locale "C.UTF-8".
timescaledb-1  | The default database encoding has accordingly been set to "UTF8".
timescaledb-1  | The default text search configuration will be set to "english".
timescaledb-1  | 
timescaledb-1  | Data page checksums are disabled.
timescaledb-1  | 
timescaledb-1  | initdb: error: could not change permissions of directory "/pgdata/data": Operation not permitted
timescaledb-1  | fixing permissions on existing directory /pgdata/data ... 
timescaledb-1 exited with code 1
```
