### ISSUE TITLE
initdb: error: could not change permissions of directory "/home/postgres/pgdata/data": Operation not permitted

### ISSUE THREAD

**Issue by dgleba** [timescale/timescaledb-docker-ha#334]
Can someone please point out what I might be doing wrong?

I am following: https://docs.timescale.com/install/latest/installation-docker/#more-docker-options

I do `docker compose up` and get the following error.

```
fixing permissions on existing directory /home/postgres/pgdata/data ... initdb: error: could not change permissions of directory "/home/postgres/pgdata/data": Operation not permitted
```

Below I have the minimal docker-compose.yml I used.

```
version: "3"
services:
  tmsc:
    image: timescale/timescaledb-ha:pg14.6-ts2.8.1-p2
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_PASSWORD=pas
    volumes:
      - ./sysdata/pgdata:/home/postgres/pgdata/data

```

Versions:

```
Linux ml-669a-hpz4 5.14.0-1054-oem #61-Ubuntu SMP Fri Oct 14 13:05:50 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"

albe@ml-669a-hpz4:/ap/dkr/timescaledb679-p/timescale679p$ dc version
Docker Compose version v2.12.2
albe@ml-669a-hpz4:/ap/dkr/timescaledb679-p/timescale679p$ docker version
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:02:21 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:00:04 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.10
  GitCommit:        770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
albe@ml-669a-hpz4:/ap/dkr/timescaledb679-p/timescale679p$

```
