### ISSUE TITLE
initdb: error: could not change permissions of directory

### ISSUE THREAD

**Issue by AlexanderProd** [timescale/timescaledb-docker-ha#460]
I'm using the latest `timescale/timescaledb-ha:pg16.2-ts2.14.2-all` Docker image, but I'm still getting the 

```
initdb: error: could not change permissions of directory "/var/lib/postgresql/data": Operation not permitted
fixing permissions on existing directory /var/lib/postgresql/data ... %                                     
``` 

error like in issue https://github.com/timescale/timescaledb-docker-ha/issues/359 when providing the `PGDATA` env variable.

My docker-compose config looks like this:

```
timescaledb16:
    image: timescale/timescaledb-ha:pg16.2-ts2.14.2-all
    volumes:
      - timescaledb16_data:/var/lib/postgresql/data
    ports:
      - '5436:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DB_NAME: xxxx
      PGUSER: xxxx
      PGPASSWORD: xxxx
      PGDATA: /var/lib/postgresql/data
```

Like described in this reply https://github.com/timescale/timescaledb-docker-ha/issues/359#issuecomment-1695094508, a workaround is to provide a local path for the volume and to manally set the permissions. 

But that doesn't work when you want to let docker handle the directory. 

Also I have notived that when ever I run `docker compose down`  and `docker compose up`  a new anonymous volume is created. Even though I have provided a named volume in the dockercompose file.

**Comment by AlexanderProd** [comment]
I found a workaround by mounting the volume to this path inside the container 
``` 
timescaledb16_data:/home/postgres/pgdata/data
```

and **not** setting the `PGDATA` env.

**Comment by jeniceek** [comment]
I've ran into same issue. Check whether you have userns-remap in Docker. If so try to add ``userns_mode: "host"`` to service definition.

**Comment by fuomag9** [comment]
Same issue with the following:

```
services:
  timescaledb:
        container_name: timescaledb
        restart: always
        ports:
            - 5432:5432
        volumes:
            - ./data:/home/postgres/pgdata/data
        environment:
            - POSTGRES_PASSWORD=password
        image: timescale/timescaledb-ha:pg16
```

**Comment by qzwzqty** [comment]
Same issue， I use Rancher Desktop.

**Comment by yuwtennis** [comment]
This still happens in [pg17-ts2.23](https://hub.docker.com/layers/timescale/timescaledb-ha/pg17-ts2.23/images/sha256-f676845c75beb13b56f1f6f9cce9a744d4f7014e10ac45ee58fb808f98a3d8ff)

## Short story 
Just stick to default [PGDATA](https://github.com/timescale/timescaledb-docker-ha/blob/1.13.2/Dockerfile#L548) . Filesystem layout is coordinated _inside_ [Dockerfile](https://github.com/timescale/timescaledb-docker-ha/blob/1.13.2/Dockerfile#L458) . 

If you are using _volume_ mount , docker compose will be something like this.  
If you want to explicitly set the PGDATA make sure you specify the place that has right permission.

```
services:
  timescaledb:
    image: 'timescale/timescaledb-ha:pg17-ts2.23'
    ports:
      - '5432:5432'
    environment:
      PGDATA: /home/postgres/pgdata/data
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - pgdata:/home/postgresql/pgdata
```

```
i.e.
[ywatanabe@lemp13 tigerdata]$ docker run --rm -it timescale/timescaledb-ha:pg17-ts2.23 ls -lR pgdata/
pgdata/:
total 8
drwxr-x--- 2 postgres postgres 4096 Nov  6 15:40 backup
drwxr-x--- 2 postgres postgres 4096 Nov  6 15:40 data
```

## Long story

Container expects to run as [postgres](https://github.com/timescale/timescaledb-docker-ha/blob/1.13.2/Dockerfile#L592) user.  This will cause the [initdb inside entryscript](https://github.com/timescale/timescaledb-docker-ha/blob/1.13.2/docker-entrypoint.sh#L120) to fail if the directory does not have right permission for _postgres_ user to modify.

In my environment, if you literally run instruction without any consideration in [official doc](https://docs.tigerdata.com/self-hosted/latest/install/installation-docker/)  using _bind_ mount fails.  

```
# docker run --name timescaledb -p 5432:5432  -v ./data:/pgdata -e PGDATA=/pgdata -e POSTGRES_PASSWORD=password timescale/timescaledb-ha:pg17-ts2.23
Waiting for permissions on /pgdata (0:0 -> 1000:1000)........................................
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "C.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /pgdata ... initdb: error: could not change permissions of directory "/pgdata": Operation not permitted

```

The script is bit imperative and monolithic so its kind a hard to figure it out.
